compatibility_date = "2025-10-02"
compatibility_flags = [
    "nodejs_compat",
    "no_handle_cross_request_promise_resolution",
]
main = "vinext/server/app-router-entry"
name = "cloesce"

[[d1_databases]]
binding = "db"
database_id = "replace_with_db_id"
database_name = "tiny-tribe-db"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "bucket"
bucket_name = "tiny-tribe-bucket"
