import type { Metadata } from "next";
import { Geist, Geist_Mono, Mulish, Outfit, Work_Sans } from "next/font/google";
import "./globals.css";

const geistSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans`}>
      {children}
    </body>
  </html>
);

export { metadata };
export default RootLayout;
